/* Generated by dbus-binding-tool; do not edit! */


#ifndef __dbus_glib_marshal_al_dbus_MARSHAL_H__
#define __dbus_glib_marshal_al_dbus_MARSHAL_H__

#include	<glib-object.h>

G_BEGIN_DECLS

#ifdef G_ENABLE_DEBUG
#define g_marshal_value_peek_boolean(v)  g_value_get_boolean (v)
#define g_marshal_value_peek_char(v)     g_value_get_char (v)
#define g_marshal_value_peek_uchar(v)    g_value_get_uchar (v)
#define g_marshal_value_peek_int(v)      g_value_get_int (v)
#define g_marshal_value_peek_uint(v)     g_value_get_uint (v)
#define g_marshal_value_peek_long(v)     g_value_get_long (v)
#define g_marshal_value_peek_ulong(v)    g_value_get_ulong (v)
#define g_marshal_value_peek_int64(v)    g_value_get_int64 (v)
#define g_marshal_value_peek_uint64(v)   g_value_get_uint64 (v)
#define g_marshal_value_peek_enum(v)     g_value_get_enum (v)
#define g_marshal_value_peek_flags(v)    g_value_get_flags (v)
#define g_marshal_value_peek_float(v)    g_value_get_float (v)
#define g_marshal_value_peek_double(v)   g_value_get_double (v)
#define g_marshal_value_peek_string(v)   (char*) g_value_get_string (v)
#define g_marshal_value_peek_param(v)    g_value_get_param (v)
#define g_marshal_value_peek_boxed(v)    g_value_get_boxed (v)
#define g_marshal_value_peek_pointer(v)  g_value_get_pointer (v)
#define g_marshal_value_peek_object(v)   g_value_get_object (v)
#else /* !G_ENABLE_DEBUG */
/* WARNING: This code accesses GValues directly, which is UNSUPPORTED API.
 *          Do not access GValues directly in your code. Instead, use the
 *          g_value_get_*() functions
 */
#define g_marshal_value_peek_boolean(v)  (v)->data[0].v_int
#define g_marshal_value_peek_char(v)     (v)->data[0].v_int
#define g_marshal_value_peek_uchar(v)    (v)->data[0].v_uint
#define g_marshal_value_peek_int(v)      (v)->data[0].v_int
#define g_marshal_value_peek_uint(v)     (v)->data[0].v_uint
#define g_marshal_value_peek_long(v)     (v)->data[0].v_long
#define g_marshal_value_peek_ulong(v)    (v)->data[0].v_ulong
#define g_marshal_value_peek_int64(v)    (v)->data[0].v_int64
#define g_marshal_value_peek_uint64(v)   (v)->data[0].v_uint64
#define g_marshal_value_peek_enum(v)     (v)->data[0].v_long
#define g_marshal_value_peek_flags(v)    (v)->data[0].v_ulong
#define g_marshal_value_peek_float(v)    (v)->data[0].v_float
#define g_marshal_value_peek_double(v)   (v)->data[0].v_double
#define g_marshal_value_peek_string(v)   (v)->data[0].v_pointer
#define g_marshal_value_peek_param(v)    (v)->data[0].v_pointer
#define g_marshal_value_peek_boxed(v)    (v)->data[0].v_pointer
#define g_marshal_value_peek_pointer(v)  (v)->data[0].v_pointer
#define g_marshal_value_peek_object(v)   (v)->data[0].v_pointer
#endif /* !G_ENABLE_DEBUG */


/* NONE:STRING,INT,BOOLEAN,POINTER */
extern void dbus_glib_marshal_al_dbus_VOID__STRING_INT_BOOLEAN_POINTER (GClosure     *closure,
                                                                        GValue       *return_value,
                                                                        guint         n_param_values,
                                                                        const GValue *param_values,
                                                                        gpointer      invocation_hint,
                                                                        gpointer      marshal_data);
void
dbus_glib_marshal_al_dbus_VOID__STRING_INT_BOOLEAN_POINTER (GClosure     *closure,
                                                            GValue       *return_value G_GNUC_UNUSED,
                                                            guint         n_param_values,
                                                            const GValue *param_values,
                                                            gpointer      invocation_hint G_GNUC_UNUSED,
                                                            gpointer      marshal_data)
{
  typedef void (*GMarshalFunc_VOID__STRING_INT_BOOLEAN_POINTER) (gpointer     data1,
                                                                 gpointer     arg_1,
                                                                 gint         arg_2,
                                                                 gboolean     arg_3,
                                                                 gpointer     arg_4,
                                                                 gpointer     data2);
  register GMarshalFunc_VOID__STRING_INT_BOOLEAN_POINTER callback;
  register GCClosure *cc = (GCClosure*) closure;
  register gpointer data1, data2;

  g_return_if_fail (n_param_values == 5);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = g_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = g_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_VOID__STRING_INT_BOOLEAN_POINTER) (marshal_data ? marshal_data : cc->callback);

  callback (data1,
            g_marshal_value_peek_string (param_values + 1),
            g_marshal_value_peek_int (param_values + 2),
            g_marshal_value_peek_boolean (param_values + 3),
            g_marshal_value_peek_pointer (param_values + 4),
            data2);
}
#define dbus_glib_marshal_al_dbus_NONE__STRING_INT_BOOLEAN_POINTER	dbus_glib_marshal_al_dbus_VOID__STRING_INT_BOOLEAN_POINTER

/* NONE:INT,POINTER */
extern void dbus_glib_marshal_al_dbus_VOID__INT_POINTER (GClosure     *closure,
                                                         GValue       *return_value,
                                                         guint         n_param_values,
                                                         const GValue *param_values,
                                                         gpointer      invocation_hint,
                                                         gpointer      marshal_data);
void
dbus_glib_marshal_al_dbus_VOID__INT_POINTER (GClosure     *closure,
                                             GValue       *return_value G_GNUC_UNUSED,
                                             guint         n_param_values,
                                             const GValue *param_values,
                                             gpointer      invocation_hint G_GNUC_UNUSED,
                                             gpointer      marshal_data)
{
  typedef void (*GMarshalFunc_VOID__INT_POINTER) (gpointer     data1,
                                                  gint         arg_1,
                                                  gpointer     arg_2,
                                                  gpointer     data2);
  register GMarshalFunc_VOID__INT_POINTER callback;
  register GCClosure *cc = (GCClosure*) closure;
  register gpointer data1, data2;

  g_return_if_fail (n_param_values == 3);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = g_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = g_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_VOID__INT_POINTER) (marshal_data ? marshal_data : cc->callback);

  callback (data1,
            g_marshal_value_peek_int (param_values + 1),
            g_marshal_value_peek_pointer (param_values + 2),
            data2);
}
#define dbus_glib_marshal_al_dbus_NONE__INT_POINTER	dbus_glib_marshal_al_dbus_VOID__INT_POINTER

/* NONE:INT,BOOLEAN,POINTER */
extern void dbus_glib_marshal_al_dbus_VOID__INT_BOOLEAN_POINTER (GClosure     *closure,
                                                                 GValue       *return_value,
                                                                 guint         n_param_values,
                                                                 const GValue *param_values,
                                                                 gpointer      invocation_hint,
                                                                 gpointer      marshal_data);
void
dbus_glib_marshal_al_dbus_VOID__INT_BOOLEAN_POINTER (GClosure     *closure,
                                                     GValue       *return_value G_GNUC_UNUSED,
                                                     guint         n_param_values,
                                                     const GValue *param_values,
                                                     gpointer      invocation_hint G_GNUC_UNUSED,
                                                     gpointer      marshal_data)
{
  typedef void (*GMarshalFunc_VOID__INT_BOOLEAN_POINTER) (gpointer     data1,
                                                          gint         arg_1,
                                                          gboolean     arg_2,
                                                          gpointer     arg_3,
                                                          gpointer     data2);
  register GMarshalFunc_VOID__INT_BOOLEAN_POINTER callback;
  register GCClosure *cc = (GCClosure*) closure;
  register gpointer data1, data2;

  g_return_if_fail (n_param_values == 4);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = g_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = g_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_VOID__INT_BOOLEAN_POINTER) (marshal_data ? marshal_data : cc->callback);

  callback (data1,
            g_marshal_value_peek_int (param_values + 1),
            g_marshal_value_peek_boolean (param_values + 2),
            g_marshal_value_peek_pointer (param_values + 3),
            data2);
}
#define dbus_glib_marshal_al_dbus_NONE__INT_BOOLEAN_POINTER	dbus_glib_marshal_al_dbus_VOID__INT_BOOLEAN_POINTER

/* NONE:STRING,INT,BOOLEAN,INT,INT,POINTER */
extern void dbus_glib_marshal_al_dbus_VOID__STRING_INT_BOOLEAN_INT_INT_POINTER (GClosure     *closure,
                                                                                GValue       *return_value,
                                                                                guint         n_param_values,
                                                                                const GValue *param_values,
                                                                                gpointer      invocation_hint,
                                                                                gpointer      marshal_data);
void
dbus_glib_marshal_al_dbus_VOID__STRING_INT_BOOLEAN_INT_INT_POINTER (GClosure     *closure,
                                                                    GValue       *return_value G_GNUC_UNUSED,
                                                                    guint         n_param_values,
                                                                    const GValue *param_values,
                                                                    gpointer      invocation_hint G_GNUC_UNUSED,
                                                                    gpointer      marshal_data)
{
  typedef void (*GMarshalFunc_VOID__STRING_INT_BOOLEAN_INT_INT_POINTER) (gpointer     data1,
                                                                         gpointer     arg_1,
                                                                         gint         arg_2,
                                                                         gboolean     arg_3,
                                                                         gint         arg_4,
                                                                         gint         arg_5,
                                                                         gpointer     arg_6,
                                                                         gpointer     data2);
  register GMarshalFunc_VOID__STRING_INT_BOOLEAN_INT_INT_POINTER callback;
  register GCClosure *cc = (GCClosure*) closure;
  register gpointer data1, data2;

  g_return_if_fail (n_param_values == 7);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = g_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = g_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_VOID__STRING_INT_BOOLEAN_INT_INT_POINTER) (marshal_data ? marshal_data : cc->callback);

  callback (data1,
            g_marshal_value_peek_string (param_values + 1),
            g_marshal_value_peek_int (param_values + 2),
            g_marshal_value_peek_boolean (param_values + 3),
            g_marshal_value_peek_int (param_values + 4),
            g_marshal_value_peek_int (param_values + 5),
            g_marshal_value_peek_pointer (param_values + 6),
            data2);
}
#define dbus_glib_marshal_al_dbus_NONE__STRING_INT_BOOLEAN_INT_INT_POINTER	dbus_glib_marshal_al_dbus_VOID__STRING_INT_BOOLEAN_INT_INT_POINTER

/* NONE:INT,INT,INT,POINTER */
extern void dbus_glib_marshal_al_dbus_VOID__INT_INT_INT_POINTER (GClosure     *closure,
                                                                 GValue       *return_value,
                                                                 guint         n_param_values,
                                                                 const GValue *param_values,
                                                                 gpointer      invocation_hint,
                                                                 gpointer      marshal_data);
void
dbus_glib_marshal_al_dbus_VOID__INT_INT_INT_POINTER (GClosure     *closure,
                                                     GValue       *return_value G_GNUC_UNUSED,
                                                     guint         n_param_values,
                                                     const GValue *param_values,
                                                     gpointer      invocation_hint G_GNUC_UNUSED,
                                                     gpointer      marshal_data)
{
  typedef void (*GMarshalFunc_VOID__INT_INT_INT_POINTER) (gpointer     data1,
                                                          gint         arg_1,
                                                          gint         arg_2,
                                                          gint         arg_3,
                                                          gpointer     arg_4,
                                                          gpointer     data2);
  register GMarshalFunc_VOID__INT_INT_INT_POINTER callback;
  register GCClosure *cc = (GCClosure*) closure;
  register gpointer data1, data2;

  g_return_if_fail (n_param_values == 5);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = g_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = g_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_VOID__INT_INT_INT_POINTER) (marshal_data ? marshal_data : cc->callback);

  callback (data1,
            g_marshal_value_peek_int (param_values + 1),
            g_marshal_value_peek_int (param_values + 2),
            g_marshal_value_peek_int (param_values + 3),
            g_marshal_value_peek_pointer (param_values + 4),
            data2);
}
#define dbus_glib_marshal_al_dbus_NONE__INT_INT_INT_POINTER	dbus_glib_marshal_al_dbus_VOID__INT_INT_INT_POINTER

/* NONE:STRING,POINTER */
extern void dbus_glib_marshal_al_dbus_VOID__STRING_POINTER (GClosure     *closure,
                                                            GValue       *return_value,
                                                            guint         n_param_values,
                                                            const GValue *param_values,
                                                            gpointer      invocation_hint,
                                                            gpointer      marshal_data);
void
dbus_glib_marshal_al_dbus_VOID__STRING_POINTER (GClosure     *closure,
                                                GValue       *return_value G_GNUC_UNUSED,
                                                guint         n_param_values,
                                                const GValue *param_values,
                                                gpointer      invocation_hint G_GNUC_UNUSED,
                                                gpointer      marshal_data)
{
  typedef void (*GMarshalFunc_VOID__STRING_POINTER) (gpointer     data1,
                                                     gpointer     arg_1,
                                                     gpointer     arg_2,
                                                     gpointer     data2);
  register GMarshalFunc_VOID__STRING_POINTER callback;
  register GCClosure *cc = (GCClosure*) closure;
  register gpointer data1, data2;

  g_return_if_fail (n_param_values == 3);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = g_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = g_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_VOID__STRING_POINTER) (marshal_data ? marshal_data : cc->callback);

  callback (data1,
            g_marshal_value_peek_string (param_values + 1),
            g_marshal_value_peek_pointer (param_values + 2),
            data2);
}
#define dbus_glib_marshal_al_dbus_NONE__STRING_POINTER	dbus_glib_marshal_al_dbus_VOID__STRING_POINTER

G_END_DECLS

#endif /* __dbus_glib_marshal_al_dbus_MARSHAL_H__ */

#include <dbus/dbus-glib.h>
static const DBusGMethodInfo dbus_glib_al_dbus_methods[] = {
  { (GCallback) al_dbus_run, dbus_glib_marshal_al_dbus_NONE__STRING_INT_BOOLEAN_POINTER, 0 },
  { (GCallback) al_dbus_run_as, dbus_glib_marshal_al_dbus_NONE__STRING_INT_BOOLEAN_INT_INT_POINTER, 86 },
  { (GCallback) al_dbus_stop, dbus_glib_marshal_al_dbus_NONE__INT_POINTER, 198 },
  { (GCallback) al_dbus_stop_as, dbus_glib_marshal_al_dbus_NONE__INT_INT_INT_POINTER, 234 },
  { (GCallback) al_dbus_resume, dbus_glib_marshal_al_dbus_NONE__INT_POINTER, 296 },
  { (GCallback) al_dbus_suspend, dbus_glib_marshal_al_dbus_NONE__INT_POINTER, 334 },
  { (GCallback) al_dbus_restart, dbus_glib_marshal_al_dbus_NONE__STRING_POINTER, 373 },
  { (GCallback) al_dbus_change_task_state, dbus_glib_marshal_al_dbus_NONE__INT_BOOLEAN_POINTER, 413 },
};

const DBusGObjectInfo dbus_glib_al_dbus_object_info = {
  0,
  dbus_glib_al_dbus_methods,
  8,
"org.GENIVI.AppL\0Run\0A\0command_line\0I\0s\0parent_pid\0I\0i\0foreground\0I\0b\0new_pid\0O\0F\0N\0i\0\0org.GENIVI.AppL\0RunAs\0A\0command_line\0I\0s\0parent_pid\0I\0i\0foreground\0I\0b\0app_uid\0I\0i\0app_gid\0I\0i\0new_pid\0O\0F\0N\0i\0\0org.GENIVI.AppL\0Stop\0A\0app_pid\0I\0i\0\0org.GENIVI.AppL\0StopAs\0A\0app_pid\0I\0i\0app_uid\0I\0i\0app_gid\0I\0i\0\0org.GENIVI.AppL\0Resume\0A\0app_pid\0I\0i\0\0org.GENIVI.AppL\0Suspend\0A\0app_pid\0I\0i\0\0org.GENIVI.AppL\0Restart\0A\0app_name\0I\0s\0\0org.GENIVI.AppL\0ChangeTaskState\0A\0app_pid\0I\0i\0foreground\0I\0b\0\0\0",
"org.GENIVI.AppL\0GlobalStateNotification\0org.GENIVI.AppL\0TaskStarted\0org.GENIVI.AppL\0TaskStopped\0org.GENIVI.AppL\0ChangeTaskStateComplete\0\0",
"\0"
};

